[pytest]
addopts = -ra
pythonpath = .
testpaths =
    selenium3_examples/tests
    selenium4_examples/tests
markers =
    selenium3: examples for Selenium 3 historical API
    selenium4: examples for Selenium 4 current API
